version: '3.8'
services:
  db:
    image: bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=postgres
    ports:
      - "5555:5432"
  app:
    restart: unless-stopped
    depends_on:
      - db
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - PORT=5000
      - ORIGIN=http://localhost:5000
      - BODY_SIZE_LIMIT=10000000
    volumes:
      - ./filesharedata:/app/data