// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package models

import (
	"time"
)

type File struct {
	CreatedAt time.Time
	UpdatedAt time.Time
	Code      string
	Filename  string
	Filesize  int64
	ExpiresAt time.Time
}
